---
title: "Proyecto 1"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)

paquetes_cran <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-07-03/paquetes_CRAN.csv")


Vamos a trabajar con el conjunto de datos `paquetes_cran` que contiene información sobre los paquetes publicados en CRAN desde 2006 a 2019.

Puedes encontrar más información sobre el conjunto de datos en https://github.com/cienciadedatos/datos-de-miercoles/blob/master/datos/2019/2019-07-03/README.md


The dataset, `olympics_top`, contains four new columns: `decade` (the decade during which the Olympics took place), `gold` (whether or not the athlete won a gold medal), `medalist` (whether or not the athlete won any medal) and `medal` (if the athlete won "Gold", "Silver", "Bronze" or received "no medal").

### **Parte 1**

**Pregunta:** ¿Cómo se comporta la cantidad de paquetes publicados en CRAN a través de los años?, ¿Existe alguna tendencia con respecto del idioma de los paquetes? 



**Introducción:** *Tu introducción va aqui*

**Enfoque:** *Tu forma de resolución va aquí*

**Analisis:**

```{r}
# Tu código de R va aquí
```

```{r}
# Tu código de R va aquí
```


**Discusión:** *Tu discusión de los resultados va aquí.*

### **Parte 2**

**Pregunta:** *Tu pregunta va a aquí*

**Introducción:** *Tu introducción va aqui*

**Enfoque:** *Tu forma de resolución va aquí*

**Analisis:**

```{r }
# Tu código de R va aquí
```

```{r }
# Tu código de R va aquí
```

**Discusión:** *Tu discusión de los resultados va aquí.*
