---
title: "Barras"
author: "Yanina"
date: '2022-04-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(datos)
```

```{r}
pinguinos %>% 
  count(especie) %>% 
  ggplot(aes(x= fct_reorder(especie, n), y= n, fill = "azul")) +
  geom_col(position = "fill", group = 1) +
  theme_classic() +
  theme(legend.position="none") +
  labs(x = "", y = "Cantidad")+
  scale_fill_manual(values = c("lightblue")) +
  coord_flip()

```

```{r}
pinguinos %>% 
  count(especie) %>% 
  ggplot(aes(x= fct_reorder(especie, n), y= n, fill = "azul")) +
  geom_col() +
  theme_classic() +
  theme(legend.position="none",
        axis.text.x = element_text(angle = 45, hjust=1)) +
  labs(x = "", y = "Cantidad")+
  scale_fill_manual(values = c("lightblue")) +
  coord_flip()

```

```{r}
pinguinos %>% 
  count(especie) %>% 
  ggplot(aes(x= especie, y= n, fill = "azul")) +
  geom_col() +
  theme_classic() +
  theme(legend.position="none") +
  labs(x = "", y = "Cantidad")+
  scale_fill_manual(values = c("lightblue")) +
  coord_flip()

```


```{r}
pinguinos %>% 
  count(especie) %>% 
  ggplot(aes(x= fct_reorder(especie, n), y= n, fill = "azul")) +
  geom_point(aes(size = 5, color = "lightblue")) +
  theme_classic() +
  theme(legend.position="none",
        axis.text.x = element_text(angle = 45, hjust=1)) +
  labs(x = "", y = "Cantidad") +
  scale_fill_manual(values = c("lightblue")) +
  coord_flip()

```

```{r}
paises %>% 
  filter(anio == 2007, continente == "Américas") %>% 
  ggplot(aes(x= fct_reorder(pais, esperanza_de_vida), y= esperanza_de_vida)) +
  geom_point(aes(size = 5, color = "rosita")) +
  theme_classic() +
  theme(legend.position="none") +
  labs(x = "") +
  coord_flip()
  

```

```{r}
paises %>% 
  filter(anio == 2007, continente == "Américas") %>% 
  ggplot(aes(x= fct_reorder(pais, esperanza_de_vida), y= esperanza_de_vida)) +
  geom_col(aes(fill = "rosita")) +
  theme_classic() +
  theme(legend.position="none") +
  labs(x = "") +
  coord_flip()

paises %>% 
  filter(anio == 2007, continente == "Américas") %>% 
  ggplot(aes(x= fct_reorder(pais, esperanza_de_vida), y= esperanza_de_vida)) +
  geom_col(aes(fill = "rosita")) +
  theme_classic() +
  theme(legend.position="none") +
  labs(x = "") +
  coord_flip(ylim = c(60, 80))

```

```{r}
pinguinos %>% 
  ggplot(aes(x=isla, y = masa_corporal_g, fill = especie))+
  geom_col(position = "dodge")+
  theme_classic()+
  labs(y = "Peso (gr)",
       x = "",
       fill = "Especie")

```

```{r}
pinguinos %>% 
  ggplot(aes(x=especie, y = masa_corporal_g, fill = isla))+
  geom_col(position = "dodge")+
  theme_classic()+
  labs(y = "Peso (gr)",
       x = "",
       fill = "Isla")

```
```{r}
pinguinos %>% 
  ggplot(aes(x=isla, y = masa_corporal_g ))+
  geom_col(position = "dodge")+
  theme_classic()+
  labs(y = "Peso (gr)",
       x = "",
       fill = "Especie")+
  facet_wrap(~especie)
```



```{r}

pinguinos %>% 
  ggplot(aes(x=isla))+
  geom_bar(aes(y = stat(prop), group = 1))+
  theme_classic()+
  labs(y = "(%)",
       x = "")
```

```{r}

pinguinos %>% 
  ggplot(aes(x=isla, fill = especie))+
  geom_bar(position = "fill")+
  theme_classic()+
  labs(y = "Cantidad",
       x = "",
       fill = "Especie")
```


